### ISSUE TITLE
stopped working since November 2019 upgrade 

### ISSUE THREAD

**Issue by rkondavei** [eapowertools/QlikSenseTask#27]
Hello, 
QliksenseTask stopped working since November 2019 upgrade. 

throwing following error message: 

2020_01_27_16_59_11,Debug,"calling https://servername.company.com/qrs/about"
2020_01_27_16_59_11,Debug,"error: The remote server returned an error: (400) Bad Request."
2020_01_27_16_59_11,Error,"System.Exception: Couldnt connect to the server at https://servername.company.com , check that the Proxy and QRS are running.  Message: The http request header is incorrect.: <!doctype html>

**Comment by rkondavei** [comment]
With SR3 and SR4

**Comment by HermodSv** [comment]
Sorry. I was to quick for this. Everything is working fine.

HS

**Comment by rkondavei** [comment]
> Sorry. I was to quick for this. Everything is working fine.
> 
> HS

really... for me it stopped since upgraded to Nov 2019 version... is there anyway to debug to find the root cause. ?

**Comment by rkondavei** [comment]
https://servername.company.com/QMC is also throwing 400 bad request The http request header is incorrect error.

**Comment by vijykiran** [comment]
any fix please, even we have been using the same , but after qlik sense Sep 2019 upgrade it is not working. Any suggestions or any other alternatives

**Comment by rkondavei** [comment]
Changed server name to fully qualified name from short name.

**Comment by vijykiran** [comment]
We are using the fully qualifier name

**Comment by rkondavei** [comment]
Did you try short name.

**Comment by vijykiran** [comment]
Yes, we have tried , but no luck
QlikSenseTask.bat -proxy:https://servername -task:Ext_LDM_DABA
QlikSenseTask.bat -proxy:https://servername.company.com -task:Ext_LDM_DABA

**Comment by rkondavei** [comment]
We are using this format : C:\QlikView\Tools\QlikSenseTask\qliksensetask -task:"TaskName" -proxy:https:// servername.company.com -wait:600"

**Comment by vijykiran** [comment]
thanks, are you using the same qliksense3. exe from this forum or any other? Which version of qlik sense?

**Comment by rkondavei** [comment]
Not sure about the version no , but we have been using the same version from dec 2017

**Comment by rkondavei** [comment]
Sorry .. I got it wrong.. we are using both QlikSense Nov 2019 and Feb 2020 version ( DEV)  attached QlikTask

**Comment by vijykiran** [comment]
is it working on qlik sense nov 2019 and feb 2020 version?

**Comment by rkondavei** [comment]
Yes it is.

**Comment by vijykiran** [comment]
Thanks Raghav, Are you using same qliksensetask from this group? 
https://github.com/eapowertools/QlikSenseTask

**Comment by rkondavei** [comment]
Yes.. its from this group

**Comment by vijykiran** [comment]
this is failing, because of this. 
2020_04_09_11_42_08,Debug,"calling https://qlikcenp1.iis.amadeus.net/qrs/about"
2020_04_09_11_42_09,Debug,"{"buildVersion":"26.2.6.0","buildDate":"10/31/2019 11:55:26 AM","databaseProvider":"Devart.Data.PostgreSql","nodeType":1,"sharedPersistence":true,"requiresBootstrap":false,"singleNodeOnly":false,"schemaPath":"About"}"
2020_04_09_11_42_09,Information,"Task is starting..."
2020_04_09_11_42_09,Error,"System.Exception: Forbidden: Forbidden
   at QlikSenseJSONObjects.QlikSenseJSONHelper.StartTaskByName(String taskname, Boolean synchronous)
   at QlikSenseTask.Program.Main(String[] args)"
2020_04_09_11_42_09,Information,"Returning Errorlevel 8"


any idea?

**Comment by marcusspitzmiller** [comment]
Hi, i have tested this against a default install of Qlik Sense April 2020 (soon to be released) and the program works.  I have no reason to suspect it wouldn't work on Feb 2020 or Nov 2019.

A 403 means that the user running QlikSenseTask has not been able to authenticate against the proxy.  A good test would be to use the same user to open a browser on the same machine and connect to the QMC, making sure the user can do so with no prompts or security warnings.

**Comment by QlikIndec** [comment]
Hello,
We are facing similar issue since many months where we are not able to reload Qliksense task using Qliksensetask tool 

Executing with CMD and we are getting error: "The underlying connection was closed: An unexpected error occurred on a send".  Find the error log below 

Can somebody suggest what can be the issue ?  Please help 

FYI, we tried using Proxy name and full name but its not working. we are currently using Feb, 2020 version for Qliksense.

Error: 
C:\Users\RootAdminAccount>F:\QlikSenseTask\QlikSenseTask -task:"Dashboard - TestQliksenseTask" -proxy:https://ServerName -wait:600"
2020_04_27_10_56_00,Information,"Task: Dashboard - TestQliksenseTask"
2020_04_27_10_56_00,Information,"Proxy: https://Servername"
2020_04_27_10_56_00,Information,"Wait: 600 seconds"
2020_04_27_10_56_00,Information,"Poll: 30 seconds"
2020_04_27_10_56_00,Information,"Log: F:\QlikSenseTask"
2020_04_27_10_56_00,Information,"Delete Log: -90 days"
2020_04_27_10_56_00,Information,"Creating connection..."
2020_04_27_10_56_00,Debug,"Creating web connection..."
2020_04_27_10_56_00,Debug,"Creating CookierAwareWebClient..."
2020_04_27_10_56_00,Debug,"calling /qrs/about"
2020_04_27_10_56_00,Debug,"setting headers"
2020_04_27_10_56_00,Debug,"constructing query string"
2020_04_27_10_56_00,Debug,"calling https://servername"
2020_04_27_10_56_00,Debug,"error: The underlying connection was closed: An unexpected error occurred on a send."
2020_04_27_10_56_00,Error,"System.Exception: Couldnt connect to the server at https://Servername , check that the Proxy and QRS are running.  Message: Object reference not set to an instance of an object.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2020_04_27_10_56_00,Information,"Returning Errorlevel 8"

**Comment by QlikSenseNL** [comment]
Hello QlikInddec,

We suddenly started to get the same error message(s) as you. Did you manage to find a solution for this? In our set-up, this might have been caused by SSL/TLS changes on the server on which QlikSense is running.

Thanks in advance.

**Comment by HermodSv** [comment]
Hi.

For me it was because a node was a little late to answer the requests. It fixed itself.



Fra: QlikSenseNL <notifications@github.com>
Sendt: onsdag 26. august 2020 12:02
Til: eapowertools/QlikSenseTask <QlikSenseTask@noreply.github.com>
Kopi: Hermod Svingerud <Hermod.Svingerud@spk.no>; Comment <comment@noreply.github.com>
Emne: Re: [eapowertools/QlikSenseTask] stopped working since November 2019 upgrade (#27)


Hello QlikInddec,

We suddenly started to get the same error message(s) as you. Did you manage to find a solution for this? In our set-up, this might have been caused by SSL/TLS changes on the server on which QlikSense is running.

Thanks in advance.
